@extends('layouts.staff')

@section('title', 'Report · '.$report->program->name)

{{-- The program report in the Manila unified format (same columns as the .xlsx): the two-row header, the
     Program cell down every row, Date / Day per day, then the program total. While the report is editable,
     Partner, Type of agency and Notes are typed right in the table. --}}
@php
    $byDay = $rows->groupBy(fn ($r) => $r->screening_date->toDateString());
    $actions = ['generated' => 'Generated', 'edited' => 'Edited details', 'submitted' => 'Submitted', 'unlock_requested' => 'Requested unlock', 'unlocked' => 'Unlocked', 'resubmitted' => 'Resubmitted'];
@endphp

@section('content')
    <header class="page-head">
        <div>
            <a class="back-link" href="{{ route('staff.program-reports.index') }}"><x-arrow dir="left" /> Program reports</a>
            <h1>{{ $report->program->name }}
                <span @class(['state', 'state--success' => $report->status === 'submitted', 'state--warning' => $report->status === 'unlocked'])>
                    {{ $report->statusLabel() }}
                </span>
            </h1>
            <p class="figures">
                <span>Generated by {{ $report->generatedBy->full_name }} · {{ $report->updated_at->format('M j, Y g:i A') }}</span>
                @if ($report->submitted_at)<span>Submitted by {{ $report->submittedBy?->full_name }} · {{ $report->submitted_at->format('M j, Y g:i A') }}</span>@endif
            </p>
        </div>
        <div class="cluster">
            <a class="btn btn--secondary" href="{{ route('staff.program-reports.export', $report) }}">Export .xlsx</a>
            @if ($editable)
                <form method="POST" action="{{ route('staff.program-reports.store') }}"
                      data-confirm="Regenerate from the current bookings and admissions? Partner, agency and notes you typed are kept.">
                    @csrf
                    <input type="hidden" name="program_id" value="{{ $report->program_id }}">
                    <button type="submit" class="btn btn--secondary">Regenerate</button>
                </form>
                <form method="POST" action="{{ route('staff.program-reports.submit', $report) }}"
                      data-confirm="Submit this report to the Super Admin? It becomes read-only until the Super Admin unlocks it." data-confirm-label="Submit report">
                    @csrf
                    <button type="submit" class="btn btn--primary">{{ $report->status === 'unlocked' ? 'Resubmit to Super Admin' : 'Submit to Super Admin' }}</button>
                </form>
            @endif
        </div>
    </header>

    {{-- Locked: the only way back is an unlock — requested by an admin, granted by the Super Admin. --}}
    @if ($report->isLocked())
        <section class="panel lock-panel" aria-labelledby="lock-title">
            <div class="lock-panel__text">
                <h2 id="lock-title">Submitted and locked</h2>
                <p>This report is read-only. @if ($pending)<strong>{{ $pending->user->full_name }}</strong> asked to unlock it {{ $pending->created_at->diffForHumans() }}: “{{ $pending->reason }}”@else To change it, the Super Admin must unlock it.@endif</p>
            </div>
            @can('unlock', $report)
                <form class="lock-panel__form" method="POST" action="{{ route('staff.program-reports.unlock', $report) }}">
                    @csrf
                    <label for="unlock-reason">Reason for unlocking <span class="req">*</span></label>
                    <textarea id="unlock-reason" name="reason" rows="2" required minlength="5" maxlength="1000">{{ old('reason') }}</textarea>
                    @error('reason') <span class="field__error">{{ $message }}</span> @enderror
                    <button type="submit" class="btn btn--primary">Unlock report</button>
                </form>
            @elsecan('requestUnlock', $report)
                <form class="lock-panel__form" method="POST" action="{{ route('staff.program-reports.request-unlock', $report) }}">
                    @csrf
                    <label for="request-reason">Why does it need to change? <span class="req">*</span></label>
                    <textarea id="request-reason" name="reason" rows="2" required minlength="5" maxlength="1000">{{ old('reason') }}</textarea>
                    @error('reason') <span class="field__error">{{ $message }}</span> @enderror
                    <button type="submit" class="btn btn--secondary">Request unlock</button>
                </form>
            @endcan
        </section>
    @endif

    <form method="POST" action="{{ route('staff.program-reports.update', $report) }}" id="report-details">
        @csrf @method('PUT')
        <div class="table-wrap manila-wrap">
            <table class="manila">
                <thead>
                <tr>
                    <th rowspan="2">Program</th><th rowspan="2">Date</th><th rowspan="2">Day</th><th rowspan="2">Time</th>
                    <th rowspan="2">Title of film</th><th rowspan="2">Admission</th><th rowspan="2">No. of films</th>
                    <th colspan="2">No. of viewers</th><th rowspan="2">PWD</th><th rowspan="2">Senior</th>
                    <th rowspan="2">Total no. of audience</th><th rowspan="2">Occupancy rate</th>
                    <th colspan="2">Tickets sold</th><th rowspan="2">Total sales</th>
                    <th rowspan="2">Partner</th><th rowspan="2">Type of agency</th><th rowspan="2">Notes</th>
                </tr>
                <tr><th>M</th><th>F</th><th>Regular</th><th>Discount</th></tr>
                </thead>
                <tbody>
                @forelse ($rows as $i => $row)
                    @php($day = $row->screening_date->toDateString())
                    @php($firstOfDay = $i === 0 || $rows[$i - 1]->screening_date->toDateString() !== $day)
                    @php($paid = $row->type === 'paid')
                    <tr>
                        @if ($i === 0)<td rowspan="{{ $rows->count() }}" class="manila__program">{{ $report->program->name }}</td>@endif
                        @if ($firstOfDay)
                            <td rowspan="{{ $byDay[$day]->count() }}" class="nowrap">{{ $row->screening_date->format('M j, Y') }}</td>
                            <td rowspan="{{ $byDay[$day]->count() }}">{{ $row->screening_date->format('D') }}</td>
                        @endif
                        <td class="nowrap">{{ \Carbon\Carbon::parse($row->start_time)->format('g:i A') }}</td>
                        <td class="manila__title">
                            @if ($row->screening_id)<a class="link-quiet" href="{{ route('staff.screenings.show', $row->screening_id) }}">{{ $row->film_title }}</a>@else{{ $row->film_title }}@endif
                        </td>
                        <td>{{ $paid ? 'Paid' : 'Free' }}</td>
                        <td class="num">{{ $row->films_count }}</td>
                        <td class="num">{{ $row->male }}</td>
                        <td class="num">{{ $row->female }}</td>
                        <td class="num">{{ $row->pwd }}</td>
                        <td class="num">{{ $row->senior }}</td>
                        <td class="num"><b>{{ $row->total_audience }}</b></td>
                        <td class="num">{{ number_format($row->occupancy_rate, 2) }}%</td>
                        <td class="num">{{ $paid ? $row->regular_count : '' }}</td>
                        <td class="num">{{ $paid ? $row->discount_count : '' }}</td>
                        <td class="num money">{{ $paid ? '₱'.number_format($row->total_sales, 2) : '' }}</td>
                        @foreach (['partner' => 150, 'agency_type' => 100, 'notes' => 2000] as $field => $max)
                            <td class="manila__input">
                                @if ($editable)
                                    <label class="sr-only" for="r{{ $row->report_row_id }}_{{ $field }}">{{ ucfirst(str_replace('_', ' ', $field)) }}, {{ $row->film_title }}</label>
                                    <input type="text" id="r{{ $row->report_row_id }}_{{ $field }}" name="rows[{{ $row->report_row_id }}][{{ $field }}]" maxlength="{{ $max }}" value="{{ old("rows.{$row->report_row_id}.{$field}", $row->{$field}) }}">
                                @else
                                    {{ $row->{$field} }}
                                @endif
                            </td>
                        @endforeach
                    </tr>
                @empty
                    <tr><td colspan="19" class="muted center">No published screenings in this program yet.</td></tr>
                @endforelse
                </tbody>
                @if ($rows->isNotEmpty())
                    <tfoot>
                    <tr>
                        <th colspan="6">Program total · {{ $totals['screenings'] }} {{ Str::plural('screening', $totals['screenings']) }}</th>
                        <td class="num">{{ $totals['films'] }}</td>
                        <td class="num">{{ $totals['male'] }}</td>
                        <td class="num">{{ $totals['female'] }}</td>
                        <td class="num">{{ $totals['pwd'] }}</td>
                        <td class="num">{{ $totals['senior'] }}</td>
                        <td class="num">{{ $totals['total_audience'] }}</td>
                        <td class="num" title="Average occupancy">{{ number_format($totals['occupancy_rate'], 2) }}%</td>
                        <td class="num">{{ $totals['regular_count'] }}</td>
                        <td class="num">{{ $totals['discount_count'] }}</td>
                        <td class="num money">₱{{ number_format($totals['total_sales'], 2) }}</td>
                        <td colspan="3"></td>
                    </tr>
                    </tfoot>
                @endif
            </table>
        </div>
        <div class="report-foot">
            <p class="hint">Viewers = admitted at the door. Occupancy = audience ÷ {{ \App\Models\Seat::CAPACITY }}.</p>
            @if ($editable && $rows->isNotEmpty())
                <button type="submit" class="btn btn--secondary">Save partner, agency and notes</button>
            @endif
        </div>
    </form>

    <section class="report-log" aria-labelledby="log-title">
        <h2 id="log-title" class="section-title">Activity</h2>
        <ol class="timeline">
            @foreach ($report->events->sortByDesc('event_id') as $event)
                <li>
                    <strong>{{ $actions[$event->action] ?? $event->action }}</strong>
                    <span class="muted small">{{ $event->user->full_name }} · {{ $event->created_at->format('M j, Y g:i A') }}</span>
                    @if ($event->reason)<span class="timeline__reason">“{{ $event->reason }}”</span>@endif
                </li>
            @endforeach
        </ol>
    </section>
@endsection
